# Generated by Django 5.1.6 on 2025-02-12 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contextitem',
            name='unique_id',
            field=models.CharField(default='000', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
