# Generated by Django 5.1.6 on 2025-02-14 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contextitem_unique_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin_city', models.CharField(max_length=255)),
                ('origin_iata', models.CharField(max_length=3)),
                ('departure_date', models.DateField()),
                ('departure_time', models.TimeField()),
                ('destiny_city', models.CharField(max_length=255)),
                ('destiny_iata', models.CharField(max_length=3)),
                ('arrive_date', models.DateField()),
                ('arrive_time', models.TimeField()),
                ('ticket_value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_id', models.CharField(max_length=255, unique=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.client')),
                ('budget_items', models.ManyToManyField(to='app.budgetitem')),
            ],
        ),
    ]
