# Generated by Django 5.1.6 on 2025-02-14 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_budgetitem_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='budget_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.budget'),
            preserve_default=False,
        ),
    ]
