# Generated by Django 5.1.6 on 2025-02-14 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_budgetitem_budget_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='client',
            new_name='client_id',
        ),
    ]
