# Generated by Django 5.1.6 on 2025-02-14 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rename_client_id_budget_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budget',
            name='budget_items',
        ),
    ]
