# Generated by Django 5.1.6 on 2025-03-14 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_budget_date_time_delete_contextitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetitem',
            name='airline',
            field=models.CharField(default='N/A', max_length=255),
            preserve_default=False,
        ),
    ]
